# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb54251d2b4d898478de0dcac75623ad7cb0cd890356af81f9076aaa7e5dfb9ec43fd5cd181421af73ad5f36e077980b08798e65952228b4a81b8b51a0174772
  host_name: http://www.freebeefor.me #Used to construct the redemptions link in ApplyStampService.rb

test:
  secret_key_base: b76996fcc8e028b6367e96864019c61cb08bbab6263b39a21ba2109080e14b21e4ecdfc5e37182540b0af7145cc85c3b7c86db3cd000f590476a85eeb9c950d1
  host_name: http://www.example.com #Used to construct the redemptions link in ApplyStampService.rb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  host_name: http://www.freebeefor.me